#!/bin/bash
set -xe
sudo sv stop kafka
sudo /etc/init.d/zookeeper-server stop
sudo rm -Rf /var/lib/zookeeper/version-2/*
sudo rm -Rf /data/{1,2,3,4,5}/kafka/*
sudo sv start kafka
sudo /etc/init.d/zookeeper-server start
sudo sv restart kafka
tail -f /etc/sv/kafka/log/main/current
